// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import 'dart:core';
import 'package:summer/src/layer/layer.dart' as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: unused_import

import 'package:reflectable/mirrors.dart' as m;
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.MethodReflectable(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'Layer',
            r'.Layer',
            134218247,
            0,
            const prefix0.MethodReflectable(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {},
            -1,
            -1,
            const <int>[-1],
            null,
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'methodInfo': 0,
              r'match': 1,
              r'name': 0,
              r'name=': 1,
              r'method': 0,
              r'method=': 1,
              r'route': 0,
              r'route=': 1,
              r'param': 0,
              r'param=': 1,
              r'keys': 0,
              r'path': 0
            })
      ],
      null,
      null,
      <Type>[prefix0.Layer],
      1,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'methodInfo': (dynamic instance) => instance.methodInfo,
        r'match': (dynamic instance) => instance.match,
        r'name': (dynamic instance) => instance.name,
        r'method': (dynamic instance) => instance.method,
        r'route': (dynamic instance) => instance.route,
        r'param': (dynamic instance) => instance.param,
        r'keys': (dynamic instance) => instance.keys,
        r'path': (dynamic instance) => instance.path
      },
      {
        r'name=': (dynamic instance, value) => instance.name = value,
        r'method=': (dynamic instance, value) => instance.method = value,
        r'route=': (dynamic instance, value) => instance.route = value,
        r'param=': (dynamic instance, value) => instance.param = value
      },
      null,
      [
        const [0, 0, null],
        const [1, 0, null],
        const [2, 0, null]
      ])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
