name: summer
description: Powerful Server Framework behind Spring. Support for route management, middleware, static file hosting, and a variety of commonly used functions
version: 0.6.5
repository: https://github.com/moluopro/summer

environment:
  sdk: ">=3.0.6 <4.0.0"

# Add regular dependencies here.
dependencies:
  path_to_regexp: ^0.4.0
  path: ^1.9.0
  mime_type: ^1.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.4
