name: summer
description: Powerful Server Framework behind Spring
version: 0.0.3
repository: https://github.com/moluopro/summer

environment:
  sdk: ">=2.12.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  path_to_regexp: ^0.4.0
  path: ^1.9.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
