baseURL = 'https://example.com/'
title = 'Summer'
theme = 'book'

disablePathToLower = true
enableGitInfo = true


[markup]
[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
startLevel = 1


[languages]

[languages.en]
languageName = 'English'
contentDir = 'content/zh'
weight = 1

[languages.zh]
languageName = '中文'
contentDir = 'content/zh'
weight = 2

[menu]
# [[menu.before]]

[[menu.after]]
name = "Github"
url = "https://github.com/moluopro/summer"
weight = 10

[[menu.after]]
name = "Pub Repo"
url = "https://pub.dev/packages/summer"
weight = 20


[params]

BookTheme = 'dark'

BookToC = true

BookFavicon = 'Summer_alpha.png'

BookLogo = 'Summer.png'

# BookSection = 'section'

BookRepo = 'https://github.com/moluopro/summer'

BookSearch = true

BookComments = true

BookPortableLinks = true

BookServiceWorker = true

BookTranslatedOnly = false
