name: summer_core
description: Core Function for Summer  
version: 0.0.1
repository: https://github.com/moluopro/summer

environment:
  sdk: ">=2.12.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
